services:
  front-api:
    container_name: front-api
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    image: front-api
    ports:
      - "4000:4000"
    networks:
      - arandu-network

  

networks:
  arandu-network:
    driver: bridge