name: Análise de Código
on:
  push:
    branches:
      - dev
      - main
      - master
  pull_request:
    branches:
      - dev
      - main
      - master

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instala dependências
        run: npm install
        
      - name: Build Next.js Application
        run: npm run build

      - name: Executa testes e gera cobertura
        run: |
          npm run test:all -- -u --no-stderr

      - name: Executa SonarCloud Scan
        if: ${{ always() }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.API_TOKEN_GITHUB}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
