name: Deploy App in Azure

# Dispara o workflow para push e pull request na branch 'dev'
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_VM_AZURE_DEV }}

      - name: Run script on Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER_VM_AZURE_DEV }}@${{ secrets.IP_VM_AZURE_DEV }} 'bash -s' < /app/run_npm_tmux.sh
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.IP_VM_AZURE_DEV }}
